name: Check Notices Every 15 Minutes
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check_notices:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Restore last notice ID
    #   uses: actions/cache@v2
    #   with:
    #     path: ./last_notice_id.txt
    #     key: ${{ runner.os }}-last-notice-id-${{ github.run_number }}
    #     restore-keys: |
    #       ${{ runner.os }}-last-notice-id-

    - name: Run notice check script
      env:
        COOKIE_VALUE: ${{ secrets.COOKIE_VALUE }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
      run: python check_notices.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add last_notice_id.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Update last_notice_id.txt"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}

    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: script-logs
        path: ${{ github.workspace }}/*.log